# Page settings

baseURL = "https://elegant-malabi-169652.netlify.app"
languageCode = "en"
title = "Minh-An TRAN"
enableGitInfo = false
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "Minh-An TRAN"
    description = "Resume"
#   og_image = "better-software.png"
    twitterName = "@bornbygoogle"
    ghRepo = "https://github.com/codewithbas/resume/"
    hugoRepo = "https://github.com/gohugoio/hugo/"

    [params.profile]
        enable = true
        name = "Minh-An TRAN"
        tagline = "Resume"
        avatar = "photo.jpg"

    [params.contact]
        enable = true

        location = "France"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:"
        text = "confidential"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:contact@minhan-tran.fr"
        text = "contact@minhan-tran.fr"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://minhan-tran.fr"
        text = "My links on the web"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = ".NET Core"
        [[params.skills.list]]
        title = ".NET Framework"
        [[params.skills.list]]
        title = "Winform"
        [[params.skills.list]]
        title = "Blazor"
        [[params.skills.list]]
        title = "PL/SQL"
        [[params.skills.list]]
        title = "Oracle"


    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Professional Bachelor's Degree in DevOps"
        university = "University of Lyon"
        dates = "2018-2019"
        [[params.education.list]]
        degree = "Information Technology (IT) Technician Diploma"
        university = "University of Lyon"
        dates = "2015-2018"


    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Professional Scrum Master™ I"
        body = "scrum.org"
        date = "2018"


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "French"
        level = "Professional skill"

        [[params.languages.list]]
        name = "English"
        level = "Professional skill"
		
		[[params.languages.list]]
        name = "Vietnamese"
        level = "Mother tongue"


    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Programming"
        [[params.interests.list]]
        name = "Technology monitoring"


    [params.summary]
        enable = true
        text = "Particularly interested in the profession of Developer, accompanied by strong motivation and effective time management while completing evening courses for my DUT in Computer Science while working full-time, I aim to apply the skills I have acquired daily by becoming a part of your teams. Beyond my skills, the adaptability I have demonstrated in the past is a quality that has contributed to my successes and one that I wish to bring to your company."


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Developper"
        dates = "2018 - Present"
        company = "AKANEA Développement"
        details = "Increased the baudrate for comic book guy"
        [[params.experience.list.items]]
        details = "Took buttery notes"



    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "This Resume"
        meta = "GitHub project"
        url = "https://github.com/codewithbas/resume"
        tagline = "A resume with a free PDF generator"


    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Cooking, Beekeeping, Cycling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/codewithbas"
        title = "/codewithbas"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/bascodes"
        title = "/in/bascodes"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "https://twitter.com/bascodes"
        title = "@bascodes"
